---
- name: "Configure mysql server"
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: su
  become_user: root

  tasks:

  - name: "Use generic package manager"
    package_facts:
      manager: auto

  - name: "mysql is installed?"
    debug:
      msg: "mysql found"
    when: "'mysql' in {{ ansible_facts.packages }}"

  - name: "mysql is installed"
    debug:
      msg: "mysql not found"
    when: "'mysql' not in {{ ansible_facts.packages }}"

  - name: "Install mysql"
    package:
      name: mysql
      state: latest

  - name: "enable mysql"
    service:
      name: mysql
      state: started
...
