---

- name: deploy_ssh
  ssh:
    hostname: '{{ inventory_hostname }}'
    username: {{ deploy_user }}
    password: "{{ password }}"
    ssh_public_key: resources/ssh/ansible.pub.pem
    ssh_port: 22

- name: check_connection
  host: '{{ inventory_hostname }}'
  wait_for:
    port: {{ ssh_port }}
    state: started
    delay: 0
    timeout: 20
    ignore_errors: yes

  #
  # tasks:
  #
  # - name: ensure app/deploy user
  #   user:
      # name: {{ deploy_user }}
      # state: present
  #   local_action: command whoami
  #   register: username_on_host

  # - name: Set authorized key taken from file
  #   authorized_key:
  #     user: {{ deploy_user }}
  #     key: "{{ lookup('file', pub_rsa_key_file) }}"
  #     state: present
  #     manage_dir: yes
  #   ignore_errors: false

  # - name: "ensure private key and public one are present"
  #   copy:
  #     src: "resources/ssh/ansible.pem"
  #     dest: "/home/{{ deploy_user }}/.ssh/{{ item }}"
  #     mode: 0600
  #   with_items:
  #     - resources/ssh/ansible.pub.pem
  #     - resources/ssh/ansible.pem

...
