- name: Install PostgreSQL
  import_tasks: "{{ module_path }}/install.yaml"

- name: Firewall for PostgreSQL
  import_tasks: "{{ module_path }}/firewall.yaml"

- name: Config PostgreSQL
  import_tasks: "{{ module_path }}/config.yaml"

- name: Backup PostgreSQL
  import_tasks: "{{ module_path }}/backup.yaml"

- name: Deploy databases
  import_tasks: "{{ module_path }}/databases.yaml"