---

- name: install yum-utils
  package:
    name: yum-utils
    state: present

- name: install docker repository
  command:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: make sure docker from distro is not installed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: Install docker
  package:
    name: docker-ce
    state: present

...