---

- hosts: all
  gather_facts: yes

  tasks:

  - name: Check ssh accessible
    wait_for:
      host: '{{ inventory_hostname }}'
      port: 22
      state: started
      delay: 0
      timeout: 20
      ignore_errors: no

...
