---

- name: Deploy ssh keys
  hosts: all
  # vars:
   # - pub_rsa_key_file: resources/ssh/ansible.pub.pem
    # - passwd: 3005
    # - deploy_user:

  roles:
    - role: ssh_copy_id
      vars:
        hostname: '{{ inventory_hostname }}'
        username: root
        password: 3005
        ssh_public_key: resources/ssh/ansible.pub.pem
        ssh_port: 22

  # tasks:
  #   - name: "Deploy SSH keys"
  #   ssh_copy_id:
  #     hostname: '{{ inventory_hostname }}'
  #     username: '{{ deploy_user }}'
  #     password: '{{ passwd }}'
  #     ssh_public_key: '{{ pub_rsa_key_file }}'
  #     ssh_port: 22

  # - name: get username running the deploy
  #   become: false
  #   local_action: command whoami
  #   register: username_on_host

  # - name: Set authorized key taken from file
  #   authorized_key:
  #     user: root #username_on_host
  #     key: "{{ lookup('file', pub_rsa_key_file) }}"
  #     state: present
  #     manage_dir: yes
  #   ignore_errors: false

  # - name: "ensure private key and public one are present"
  #   copy:
  #     src: "resources/ssh/ansible.pem"
  #     dest: "/home/{{ deploy_user }}/.ssh/{{ item }}"
  #     mode: 0600
  #   with_items:
  #     - resources/ssh/ansible.pub.pem
  #     - resources/ssh/ansible.pem

...
