---

- hosts: all
  gather_facts: yes
  vars:
    pub_rsa_key_file: "/resources/ssh/ansible.pub.pem"

  tasks:

  - name: get username running the deploy
    become: false
    local_action: command whoami
    register: username_on_host

  - name: Set authorized key taken from file
    authorized_key:
      user: username_on_host
      state: present
      key: "{{ lookup('file', pub_rsa_key_file) }}"

  - name: "Check ssh accessible"
    wait_for:
      host: '{{ inventory_hostname }}'
      port: 22
      state: started
      delay: 0
      timeout: 20
      ignore_errors: no

...
