all:
  hosts:
    localhost:
  children:
    real:
      127.0.0.1:
    virtual:
      vagrant:
        {}
      wmvare:
        {}
      container:
        docker:
          - 172.18.0.1
          - 172.18.0.2
          - 172.18.0.3
        dockerhub:
          - 172.19.0.1
        kubernetes:
          - 172.20.0.1
