---
- name: "Configure mysql server"
  hosts: 127.0.0.1
  connection: local
  tasks:
        - name: "Check if mysql is installed"
          package_facts:
                manger: auto
        - name: "mysql test result"
          debug:
                msg: "mysql found"
          when: "'mysql' in ansible_facts.packages"
         
        - name: "mysql test result"
          debug:
                 msg: "mysql not found"
        - name: "Installing mysql"
          package:
                name: mysql
                state: latest
          when: "'mysql' not in ansible_facts.packages"

        - name: "enable mysql"
          service:
                  name: mysql
                  state: started
...
